Throw an exception if no symlink support is present

diff --git a/archi b/archi
--- a/archi
+++ b/archi
@@ -1417,6 +1417,16 @@ ZIPALIGN="./tools/zipalign/$HOSTARCH/zipalign"
 # Navigate to our folder, even if user didn't execute it from the root dir
 cd "$(dirname "$0")"
 
+# Check if symlink support is present
+if [[ "$(ln -s archi archi.ln.test)" -ne 0 ]]; then
+	echo "ERROR: Current kitchen location doesn't support symbolic links!"
+	echo "Symbolic links cannot be used on Windows-based filesystems, such as FAT, NTFS, or VirtualBox shared folder mount on one of the previous"
+	echo" You must use ArchiKitchen in native Linux location, such as /root, /home/username, /tmp, or any other mountpoint, which supports symbolic links"
+	exit 1
+else
+	rm -f archi.ln.test
+fi
+
 # Create our temporary directory
 mkdir -p "$TEMPDIR"
 
