Misc update

diff --git a/archi b/archi
--- a/archi
+++ b/archi
@@ -1,5 +1,5 @@
-﻿#!/bin/bash
- 
+﻿#!/usr/bin/env bash
+
 # Copyright 2014 JustArchi@JustArchi.net
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
@@ -19,6 +19,8 @@ set +e
 # Initial variables
 VERSION="1.0"
 TOOLS=(which realpath whoami basename dirname gcc java perl sed cut wget od wc cpio zip unzip tar)
+XDALINK="http://forum.xda-developers.com/showthread.php?t=2597220"
+
 ACTIVE_PROJECT=""
 ARCH="arm"
 ALIGN=4
@@ -29,6 +31,7 @@ UPDATER_SCRIPT_HEAD="updater-script-00_HEAD"
 UPDATER_SCRIPT_SYMLINKS="updater-script-10_SYMLINKS"
 UPDATER_SCRIPT_PERMISSIONS="updater-script-20_PERMISSIONS"
 UPDATER_SCRIPT_EXEC="updater-script-80_EXEC"
+UPDATER_SCRIPT_USER="updater-script-85_USER"
 UPDATER_SCRIPT_KERNEL="updater-script-90_KERNEL"
 UPDATER_SCRIPT_MODEM="updater-script-91_MODEM"
 UPDATER_SCRIPT_TAIL="updater-script-99_TAIL"
@@ -65,18 +68,18 @@ PRESS_ENTER() {
 	read -p "Press [Enter] key to continue..."
 }
 
-# Executes commands given in $@ as root
+# Executes commands given in arguments as root
 ROOT_EXECUTE() {
 	local CHOICE="y"
 	while [ "$CHOICE" != "n" ] && [ "$CHOICE" != "N" ]; do
-		if [ $(whoami) == "root" ]; then
-			$@
+		if [ "$CUSER" == "root" ]; then
+			$*
 		else
 			echo "Root access is required! I'm about to execute command $@"
 			if [ ! -z $(which sudo) ]; then
-				sudo $@
+				sudo $*
 			else
-				su -c $@
+				su -c $*
 			fi
 		fi
 		if [ $? -eq 0 ]; then
@@ -85,10 +88,11 @@ ROOT_EXECUTE() {
 			read -p "Sorry, something went wrong, error code: $?. Would you like to try again? [Y/n]: " CHOICE
 		fi
 	done
-	if [ "$CHOICE" == "n" ] || [ "$CHOICE" == "N" ]; then
-		echo "Aborting..."
-		exit 1
-	fi
+	case "$CHOICE" in
+		n|N)
+			echo "Aborting..."
+			exit 1
+	esac
 }
 
 # Sets ACTIVE_PROJECT
@@ -267,7 +271,7 @@ DO_NEWPROJECT() {
 					;;
 			esac
 			echo
-			read -p "Include? [y/n]: " CHOICE
+			read -p "Include? [Y/n]: " CHOICE
 			case "$CHOICE" in
 				n|N) ;;
 				*) cp $SYSTEMDIR/$EXTRA $ACTIVE_PROJECT/$EXTRA
@@ -432,9 +436,13 @@ UPDATER_SCRIPT_DEL() {
 
 # Builds final updater-script from our segments
 BUILD_UPDATER_SCRIPT() {
+	local HEADER=""
 	echo -n "" > $ACTIVE_PROJECT/$META_INF/updater-script
 	for UPDATER_SCRIPT in $ACTIVE_PROJECT/$META_INF/updater-script-*; do
+		HEADER="# "
+		HEADER+=$(basename "$UPDATER_SCRIPT")
 		echo "" >> $ACTIVE_PROJECT/$META_INF/updater-script # This is to ensure that we have a new line BEFORE appending"
+		echo "$HEADER" >> "$ACTIVE_PROJECT/$META_INF/updater-script"
 		cat "$UPDATER_SCRIPT" >> "$ACTIVE_PROJECT/$META_INF/updater-script"
 		echo "" >> $ACTIVE_PROJECT/$META_INF/updater-script # This is to ensure that we have a new line AFTER appending"
 	done
@@ -477,7 +485,7 @@ FIX_PERMISSIONS() {
 
 # Removes invalid generic symlinks, adds local ones
 FIX_SYMLINKS() {
-	echo "Right now you're using generic list of symlinks based on multiple devices"
+	echo "Right now you're probably using generic list of symlinks based on multiple devices"
 	echo "It's usually a good idea to remove invalid symlinks, by invalid I mean symlinks to non-existent files or folders"
 	read -p "Do you want to remove invalid symlinks? [Y/n]: " CHOICE
 	case "$CHOICE" in
@@ -655,23 +663,32 @@ INITD() {
 
 BUILD() {
 	local IGNOREDFILES="$META_INF/updater-script-*"
-	FIX_PERMISSIONS
-	FIX_SYMLINKS
-	BUILD_UPDATER_SCRIPT
-	echo "Sometimes kitchen may produce an incorrect updater-script file, that's why you're asked to review updater-script and eventually fix it if needed BEFORE building ROM"
-	echo "Updater-script is based on so-called 'segments' available in the same directory - $META_INF"
-	echo "Are you ready?"
-	PRESS_ENTER
-	echo "-=-= UPDATER-SCRIPT START =-=-"
-	cat $ACTIVE_PROJECT/$META_INF/updater-script
-	echo "-=-= UPDATER-SCRIPT EOF =-=-"
-	read -p "Are you REALLY sure that above updater-script is correct? ESPECIALLY block-based paths? [y/n]: " CHOICE
-	case "$CHOICE" in
-		n|N)
-			echo "OK, correct your updater-script and/or it's segments and come back when you're finished"
-			PRESS_ENTER
-			return 0
-	esac
+	local EXPERT=false
+	for ARG in $@; do
+		case "$ARG" in
+			"EXPERT")
+				EXPERT=true
+		esac
+	done
+	if !($EXPERT); then
+		FIX_PERMISSIONS
+		FIX_SYMLINKS
+		BUILD_UPDATER_SCRIPT
+		echo "Sometimes kitchen may produce an incorrect updater-script file, that's why you're asked to review updater-script and eventually fix it if needed BEFORE building ROM"
+		echo "Updater-script is based on so-called 'segments' available in the same directory - $META_INF"
+		echo "Are you ready?"
+		PRESS_ENTER
+		echo "-=-= UPDATER-SCRIPT START =-=-"
+		cat $ACTIVE_PROJECT/$META_INF/updater-script
+		echo "-=-= UPDATER-SCRIPT EOF =-=-"
+		read -p "Are you REALLY sure that above updater-script is correct? ESPECIALLY block-based paths? [Y/n]: " CHOICE
+		case "$CHOICE" in
+			n|N)
+				echo "OK, correct your updater-script and/or it's segments and come back when you're finished"
+				PRESS_ENTER
+				return 0
+		esac
+	fi
 	local COMPLEVEL="1"
 	echo
 	echo "Which compression level do you want to use?"
@@ -689,10 +706,9 @@ BUILD() {
 	mkdir -p OUTPUT_ZIP
 	mv -f $ACTIVE_PROJECT/$ACTIVE_PROJECT.zip OUTPUT_ZIP/$ACTIVE_PROJECT.zip
 	echo "Done, your ROM is available in OUTPUT_ZIP/$ACTIVE_PROJECT.zip"
-	read -p "Rename it? [y/n]: " CHOICE
+	read -p "Rename it? [N/y]: " CHOICE
 	case "$CHOICE" in
-		n|N) ;;
-		*)
+		y|Y)
 			read -p "New name: " NAME
 			mv -f OUTPUT_ZIP/$ACTIVE_PROJECT.zip OUTPUT_ZIP/$NAME
 	esac
@@ -706,10 +722,9 @@ DEODEX() {
 	local API=$(grep "ro.build.version.sdk" $ACTIVE_PROJECT/system/build.prop | cut -d'=' -f2)
 	echo "Detected API level $API"
 	echo "Usually you don't want to change this value"
-	read -p "Change it? [y/n]: " CHOICE
+	read -p "Change it? [N/y]: " CHOICE
 	case "$CHOICE" in
-		n|N) ;;
-		*) read -p "Your selected API level: " API
+		y|Y) read -p "Your selected API level: " API ;;
 	esac
 	case "$API" in
 		[0-9]*) ;;
@@ -820,101 +835,35 @@ ADB() {
 	fi
 }
 
-###############################################################
-# ____  _____ ____  ____  _____ ____    _  _____ _____ ____   #
-#|  _ \| ____|  _ \|  _ \| ____/ ___|  / \|_   _| ____|  _ \  #
-#| | | |  _| | |_) | |_) |  _|| |     / _ \ | | |  _| | | | | #
-#| |_| | |___|  __/|  _ <| |__| |___ / ___ \| | | |___| |_| | #
-#|____/|_____|_|   |_| \_\_____\____/_/   \_\_| |_____|____/  #
-#                                                             #
-###############################################################
-REBUILD_UPDATER-SCRIPT() {
-	# DEPRECATED -> UPDATER_SCRIPT_ADD & UPDATER_SCRIPT_DEL
-	local MODE=""
-	local STYLE=""
-	local FILE=""
-	for arg in $@; do
-		case "$arg" in
-			"ADD")
-				MODE="ADD"
-				shift 1
-				;;
-			"DEL")
-				MODE="DEL"
-				shift 1
-				;;
-			"HEAD")
-				FILE="$UPDATER_SCRIPT_HEAD"
-				shift 1
-				;;
-			"SYMLINKS")
-				FILE="$UPDATER_SCRIPT_SYMLINKS"
-				shift 1
-				;;
-			"PERMISSIONS")
-				FILE="$UPDATER_SCRIPT_PERMISSIONS"
-				shift 1
-				;;
-			"EXEC")
-				FILE="$UPDATER_SCRIPT_EXEC"
-				shift 1
-				;;
-			"TAIL")
-				FILE="$UPDATER_SCRIPT_TAIL"
-				shift 1
-				;;
-			"KERNEL")
-				FILE="$UPDATER_SCRIPT_KERNEL"
-				shift 1
-				;;
-			"MODEM")
-				FILE="updater-script-91_MODEM"
-				shift 1
-				;;
-			"APPEND")
-				STYLE="APPEND"
-				shift 1
-				;;
-			"PREPEND")
-				STYLE="PREPEND"
-				shift 1
-				;;
-		esac
-	done
-	if [ $MODE == "DEL" ]; then
-		#TODO1: We're handling it through so-called "primary key" but this needs to be implemented in a better way, as it's dangerous
-		sed -i "/$@/d" $ACTIVE_PROJECT/$META_INF/$FILE
-		shift 1
-	elif [ $MODE == "ADD" ]; then
-		if [ $STYLE == "APPEND" ]; then
-			echo "" >> $ACTIVE_PROJECT/$META_INF/$FILE
-			cat "$@" >> $ACTIVE_PROJECT/$META_INF/$FILE
-			echo "" >> $ACTIVE_PROJECT/$META_INF/$FILE
-		elif [ $STYLE == "PREPEND" ]; then
-			mv $ACTIVE_PROJECT/$META_INF/$FILE $ACTIVE_PROJECT/$META_INF/$FILE.tmp
-			cat "$@" > $ACTIVE_PROJECT/$META_INF/$FILE
-			echo "" >> $ACTIVE_PROJECT/$META_INF/$FILE
-			cat $ACTIVE_PROJECT/$META_INF/$FILE.tmp >> $ACTIVE_PROJECT/$META_INF/$FILE
-			rm -f $ACTIVE_PROJECT/$META_INF/$FILE.tmp
-		fi
-	fi
-	sed -i '/^$/d' $ACTIVE_PROJECT/$META_INF/$FILE # This removes empty lines added above
-	#BUILD_UPDATER_SCRIPT # We handle that through scripts itself, as it causes up to 4x non-needed overhead
-}
+################################################################
+#  ____  _____ ____  ____  _____ ____    _  _____ _____ ____   #
+# |  _ \| ____|  _ \|  _ \| ____/ ___|  / \|_   _| ____|  _ \  #
+# | | | |  _| | |_) | |_) |  _|| |     / _ \ | | |  _| | | | | #
+# | |_| | |___|  __/|  _ <| |__| |___ / ___ \| | | |___| |_| | #
+# |____/|_____|_|   |_| \_\_____\____/_/   \_\_| |_____|____/  #
+#                                                              #
+################################################################
 
-# Main
+############################
+#   ____ ___  ____  _____  #
+#  / ___/ _ \|  _ \| ____| #
+# | |  | | | | |_) |  _|   #
+# | |__| |_| |  _ <| |___  #
+#  \____\___/|_| \_\_____| #
+#                          #
+############################
 while :; do
 	clear
 
-	echo "Android Kitchen version $VERSION - by JustArchi (@xda-developers.com)"
-	echo "Originally created by dsixda (@xda-developers.com)"
+	echo "ArchiKitchen version $VERSION - developed by JustArchi"
+	echo "Original thread: $XDALINK"
 	echo
 	if [ -z "$ACTIVE_PROJECT" ]; then
 		DO_SETPROJECT
 		continue
 	fi
 
-	echo "-------------------------------------"
+	echo "--------------------------------------------------------------------------------"
 	ALLFINE=true
 	if [ -d $ACTIVE_PROJECT/kernel ]; then
 		ALLFINE=false
@@ -934,9 +883,8 @@ while :; do
 	else
 		echo "WARNING"
 	fi
-	echo "-------------------------------------"
+	echo "--------------------------------------------------------------------------------"
 
-	echo
 	echo "Architecture: [$ARCH] "
 	echo
 
@@ -946,7 +894,6 @@ while :; do
 	else
 		echo "[YES]"
 	fi
-	echo
 	echo -n "Deodexed? "
 	if [ -e $ACTIVE_PROJECT/system/framework/framework.odex ]; then
 		echo "[NO]"
@@ -973,10 +920,7 @@ while :; do
 		echo "[YES]"
 	fi
 	if [ -e $ACTIVE_PROJECT/kernel/ramdisk ]; then
-		echo
-		echo "-=-=-=-="
-		echo '|Kernel|'
-		echo "-=-=-=-="
+		echo "--------------------------------------------------------------------------------"
 		echo -n "ADB? "
 		if [ $(grep "ro.adb.secure=0" $ACTIVE_PROJECT/kernel/ramdisk/default.prop | wc -l) -gt 0 ]; then
 			echo "[INSECURE]"
@@ -990,32 +934,28 @@ while :; do
 			echo "[NO]"
 		fi
 	fi
-	echo
-	echo "-------------------------------------------------------------------------------"
+	echo "--------------------------------------------------------------------------------"
 	echo "a	- Change architecture (arm/x86)"
 	echo
-	echo "adi	- Enable/Disable ArchiDroid indepdendent Init.d (software debuggerd hook)"
+	echo "adi	- Enable/Disable ArchiDroid Init.d (software debuggerd hook)"
 	echo
 	echo "d	- Deodex Everything"
 	echo "z	- Zipalign Everything"
 	echo "r	- Enable/Disable Root"
 	echo "b	- Enable/Disable Busybox"
-	echo
-	echo "-=-=-=-="
-	echo '|Kernel|'
-	echo "-=-=-=-="
+	echo "-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-"
 	if [ -e $ACTIVE_PROJECT/kernel/ramdisk ]; then
-		echo "kr	- Repack kernel"
 		echo "ka	- Abort repacking of kernel (lose all kernel changes selected below)"
 		echo "i	- Add Init.d Support (Bugged?) (hardware kernel hook)"
 		echo "adb	- Enable/Disable insecure ADB"
-	else
+	elif [ -e $ACTIVE_PROJECT/boot.img ]; then
 		echo "ku	- Unpack kernel (this enables more options!)"
 	fi
-	echo
-	echo "bb	- Build ROM"
+	echo "-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-"
+	echo "bb	- Build ROM (normal suggested mode)"
+	echo "bbe	- Build ROM (expert mode, won't make any checks if your project is OK)"
 	echo "x	- Exit"
-	echo
+	echo "--------------------------------------------------------------------------------"
 	echo -n "CHOICE: "
 	read CHOICE
 	case "$CHOICE" in
@@ -1063,5 +1003,8 @@ while :; do
 				PRESS_ENTER
 			fi
 			;;
+		bbe|BBE)
+			BUILD "EXPERT"
+		;;
 	esac
 done
