Add multi-threaded support for zipaligning

diff --git a/archi b/archi
--- a/archi
+++ b/archi
@@ -23,8 +23,10 @@ XDALINK="http://forum.xda-developers.com/showthread.php?t=2597220"
 
 ACTIVE_PROJECT=""
 ARCH="arm"
-ALIGN=4
 CUSER=$(whoami)
+
+ALIGN=4
+FULLPERFORMANCE=true
 
 META_INF="META-INF/com/google/android"
 UPDATER_SCRIPT_HEAD="updater-script-00_HEAD"
@@ -778,13 +780,25 @@ DEODEX() {
 	PRESS_ENTER
 }
 
+ZIPALIGN_APK() {
+	echo "Zipaligning $(basename "$1")..."
+	./tools/zipalign/zipalign -f "$ALIGN" "$1" "$1.zipaligned" >/dev/null 2>&1 && mv -f "$1.zipaligned" "$1"
+	return $?
+}
+
 ZIPALIGN() {
-	for APK in $(find $ACTIVE_PROJECT/system -type f -iname "*.apk"); do
-		echo "Zipaligning $(basename $APK)..."
-		./tools/zipalign/zipalign -f "$ALIGN" "$APK" "$APK.zipaligned" && mv -f "$APK.zipaligned" "$APK"
-	done
+	if ($FULLPERFORMANCE); then
+		for APK in $(find $ACTIVE_PROJECT/system -type f -iname "*.apk"); do
+			ZIPALIGN_APK "$APK" &
+		done
+		wait
+	else
+		for APK in $(find $ACTIVE_PROJECT/system -type f -iname "*.apk"); do
+			ZIPALIGN_APK "$APK"
+		done
+	fi
 	echo
-	echo "Zipaligning finished"
+	echo "Zipaligning finished!"
 	PRESS_ENTER
 }
 
@@ -833,35 +847,13 @@ ADB() {
 	fi
 }
 
-################################################################
-#  ____  _____ ____  ____  _____ ____    _  _____ _____ ____   #
-# |  _ \| ____|  _ \|  _ \| ____/ ___|  / \|_   _| ____|  _ \  #
-# | | | |  _| | |_) | |_) |  _|| |     / _ \ | | |  _| | | | | #
-# | |_| | |___|  __/|  _ <| |__| |___ / ___ \| | | |___| |_| | #
-# |____/|_____|_|   |_| \_\_____\____/_/   \_\_| |_____|____/  #
-#                                                              #
-################################################################
-
-############################
-#   ____ ___  ____  _____  #
-#  / ___/ _ \|  _ \| ____| #
-# | |  | | | | |_) |  _|   #
-# | |__| |_| |  _ <| |___  #
-#  \____\___/|_| \_\_____| #
-#                          #
-############################
-while :; do
-	clear
-
+PRINT_BANNER() {
 	echo "ArchiKitchen version $VERSION - developed by JustArchi"
 	echo "Original thread: $XDALINK"
-	echo
-	if [ -z "$ACTIVE_PROJECT" ]; then
-		DO_SETPROJECT
-		continue
-	fi
-
 	echo "--------------------------------------------------------------------------------"
+}
+
+PRINT_PROJECT_STATUS() {
 	ALLFINE=true
 	if [ -d $ACTIVE_PROJECT/kernel ]; then
 		ALLFINE=false
@@ -882,7 +874,9 @@ while :; do
 		echo "WARNING"
 	fi
 	echo "--------------------------------------------------------------------------------"
+}
 
+PRINT_ROM_STATUS() {
 	echo "Architecture: [$ARCH] "
 	echo
 
@@ -933,6 +927,9 @@ while :; do
 		fi
 	fi
 	echo "--------------------------------------------------------------------------------"
+}
+
+PRINT_SWITCHES() {
 	echo "a	- Change architecture (arm/x86)"
 	echo
 	echo "adi	- Enable/Disable ArchiDroid Init.d (software debuggerd hook)"
@@ -943,7 +940,9 @@ while :; do
 	echo "b	- Enable/Disable Busybox"
 	echo "-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-"
 	if [ -e $ACTIVE_PROJECT/kernel/ramdisk ]; then
-		echo "ka	- Abort repacking of kernel (lose all kernel changes selected below)"
+		echo "kr	- Repack kernel (apply all ramdisk changes)"
+		echo "ka	- Abort repacking (abort all ramdisk changes)"
+		echo
 		echo "i	- Add Init.d Support (Bugged?) (hardware kernel hook)"
 		echo "adb	- Enable/Disable insecure ADB"
 	elif [ -e $ACTIVE_PROJECT/boot.img ]; then
@@ -952,47 +951,92 @@ while :; do
 	echo "-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-"
 	echo "bb	- Build ROM (normal suggested mode)"
 	echo "bbe	- Build ROM (expert mode, won't make any checks if your project is OK)"
+	echo "--------------------------------------------------------------------------------"
+	echo "ak	- Change ArchiKitchen settings"
 	echo "x	- Exit"
 	echo "--------------------------------------------------------------------------------"
-	echo -n "CHOICE: "
-	read CHOICE
+}
+
+PAGE_SETTINGS() {
+	while :; do
+		clear
+		PRINT_BANNER
+		echo -n "Full performance: "
+		if ($FULLPERFORMANCE); then
+			echo "[YES]"
+		else
+			echo "[NO]"
+		fi
+		echo "--------------------------------------------------------------------------------"
+		echo "Full performance mode tries to finish common ArchiKitchen tasks ASAP"
+		echo "This includes i.e. calling all job threads at once and waiting for them to"
+		echo "finish instead of calling them one-by-one and blocking main thread"
+		echo "Due to that, OS may become unresponsive when ArchiKitchen is performing a task"
+		echo "Usually it's a good idea to keep it ON, unless you have a very good reason"
+		echo "for forcing ArchiKitchen to run in a single-thread mode"
+		echo "--------------------------------------------------------------------------------"
+		echo "p	- Full performance switch"
+		echo "x	- Go back"
+		echo "--------------------------------------------------------------------------------"
+		read -p "CHOICE: " CHOICE
+		case "$CHOICE" in
+			p|P)
+				if ($FULLPERFORMANCE); then
+					FULLPERFORMANCE=false
+				else
+					FULLPERFORMANCE=true
+				fi
+				;;
+			x|X) return 0
+		esac
+	done
+}
+
+################################################################
+#  ____  _____ ____  ____  _____ ____    _  _____ _____ ____   #
+# |  _ \| ____|  _ \|  _ \| ____/ ___|  / \|_   _| ____|  _ \  #
+# | | | |  _| | |_) | |_) |  _|| |     / _ \ | | |  _| | | | | #
+# | |_| | |___|  __/|  _ <| |__| |___ / ___ \| | | |___| |_| | #
+# |____/|_____|_|   |_| \_\_____\____/_/   \_\_| |_____|____/  #
+#                                                              #
+################################################################
+
+############################
+#   ____ ___  ____  _____  #
+#  / ___/ _ \|  _ \| ____| #
+# | |  | | | | |_) |  _|   #
+# | |__| |_| |  _ <| |___  #
+#  \____\___/|_| \_\_____| #
+#                          #
+############################
+while :; do
+	clear
+
+	PRINT_BANNER
+
+	if [ -z "$ACTIVE_PROJECT" ]; then
+		DO_SETPROJECT
+		continue
+	fi
+
+	PRINT_PROJECT_STATUS
+	PRINT_ROM_STATUS
+	PRINT_SWITCHES
+	read -p "CHOICE: " CHOICE
 	case "$CHOICE" in
-		x|X)
-			exit 0
-			;;
-		a|A)
-			CHANGE_ARCHITECTURE
-			;;
-		adi|ADI)
-			ARCHIDROID_INITD
-			;;
-		d|D)
-			DEODEX
-			;;
-		z|Z)
-			ZIPALIGN
-			;;
-		r|R)
-			ROOT
-			;;
-		b|B)
-			BUSYBOX
-			;;
-		i|I)
-			INITD
-			;;
-		adb|ADB)
-			ADB
-			;;
-		ku|KU)
-			KERNEL_EXTRACT
-			;;
-		kr|KR)
-			KERNEL_REPACK
-			;;
-		ka|KA)
-			KERNEL_ABORT
-			;;
+		ak|AK) PAGE_SETTINGS ;;
+		a|A) CHANGE_ARCHITECTURE ;;
+		adi|ADI) ARCHIDROID_INITD ;;
+		d|D) DEODEX ;;
+		z|Z) ZIPALIGN ;;
+		r|R) ROOT ;;
+		b|B) BUSYBOX ;;
+		i|I) INITD ;;
+		adb|ADB) ADB ;;
+		ku|KU) KERNEL_EXTRACT ;;
+		kr|KR) KERNEL_REPACK ;;
+		ka|KA) KERNEL_ABORT ;;
+		bbe|BBE) BUILD "EXPERT" ;;
 		bb|BB)
 			if ($ALLFINE); then
 				BUILD
@@ -1001,8 +1045,6 @@ while :; do
 				PRESS_ENTER
 			fi
 			;;
-		bbe|BBE)
-			BUILD "EXPERT"
-		;;
+		x|X) exit 0
 	esac
 done
