Add root and deodex

diff --git a/archi b/archi
--- a/archi
+++ b/archi
@@ -318,21 +318,24 @@ REBUILD_UPDATER-SCRIPT() {
 		esac
 	done
 	if [ $MODE == "DEL" ]; then
-		#TODO: Handle this through $@? Couldn't find non-conflict way
-		sed -i "/$1/d" $ACTIVE_PROJECT/META-INF/com/google/android/$FILE
+		#TODO1: We're handling it through so-called "primary key" but this needs to be implemented in a better way, as it's dangerous
+		sed -i "/$@/d" $ACTIVE_PROJECT/META-INF/com/google/android/$FILE
 		shift 1
 	elif [ $MODE == "ADD" ]; then
 		if [ $STYLE == "APPEND" ]; then
 			echo "" >> $ACTIVE_PROJECT/META-INF/com/google/android/$FILE
-			echo "$@" >> $ACTIVE_PROJECT/META-INF/com/google/android/$FILE
+			cat "$@" >> $ACTIVE_PROJECT/META-INF/com/google/android/$FILE
+			echo "" >> $ACTIVE_PROJECT/META-INF/com/google/android/$FILE
 		elif [ $STYLE == "PREPEND" ]; then
 			mv $ACTIVE_PROJECT/META-INF/com/google/android/$FILE $ACTIVE_PROJECT/META-INF/com/google/android/$FILE.tmp
-			echo "$@" > $ACTIVE_PROJECT/META-INF/com/google/android/$FILE
+			cat "$@" > $ACTIVE_PROJECT/META-INF/com/google/android/$FILE
+			echo "" >> $ACTIVE_PROJECT/META-INF/com/google/android/$FILE
 			cat $ACTIVE_PROJECT/META-INF/com/google/android/$FILE.tmp >> $ACTIVE_PROJECT/META-INF/com/google/android/$FILE
 			rm -f $ACTIVE_PROJECT/META-INF/com/google/android/$FILE.tmp
 		fi
 	fi
-	#BUILD_UPDATER_SCRIPT
+	sed -i '/^$/d' $ACTIVE_PROJECT/META-INF/com/google/android/$FILE # This removes empty lines added above
+	#BUILD_UPDATER_SCRIPT # We handle that through scripts itself, as it causes up to 4x non-needed overhead
 }
 
 BUILD_UPDATER_SCRIPT() {
@@ -349,16 +352,82 @@ CLEAN_EVERYTHING() {
 	done
 }
 
+DEODEX() {
+	local API=$(grep "ro.build.version.sdk" $ACTIVE_PROJECT/system/build.prop | cut -d'=' -f2)
+	echo "Detected API level $API"
+	for f in $(find $ACTIVE_PROJECT/system -type f -iname "*.odex"); do
+		local FILE=$(basename $f)
+		local FILEDIR=$(dirname $f)
+		echo "Deodxing $FILE"
+		echo "Disassembling $FILE..."
+		java -Xmx512m -jar files/smali/baksmali.jar -a $API -d $ACTIVE_PROJECT/system/framework -x $FILEDIR/$FILE
+		if [ $? -ne 0 ]; then
+			echo "ERROR DEODEXING $FILE, ABORTING!"
+			rm -rf out
+			PRESS_ENTER
+			return 1
+		fi
+		echo "Assembling into classes.dex..."
+		java -Xmx512m -jar files/smali/smali.jar -a $API -o classes.dex out
+		if [ ! -e classes.dex ]; then
+			echo "ERROR DEODEXING $FILE, ABORTING!"
+			rm -rf out
+			PRESS_ENTER
+			return 1
+		fi
+		FILE=$(echo $FILE | rev | cut -d'.' -f2- | rev)
+		local FOUND=false
+		for EXTENSION in "jar" "apk"; do
+			if [ -e $FILEDIR/$FILE.$EXTENSION ]; then
+				echo "Packing back into $FILE.$EXTENSION..."
+				zip -rq $FILEDIR/$FILE.$EXTENSION classes.dex
+				rm -f classes.dex
+				FOUND=true
+				break
+			fi
+		done
+		if (! $FOUND); then
+			echo "ERROR, No output found?!"
+			rm -rf out
+			rm -f classes.dex
+			PRESS_ENTER
+			return 1
+		fi
+		rm -f $f
+		rm -rf out
+	done
+}
+
+ROOT() {
+	if [ ! -e $ACTIVE_PROJECT/system/xbin/su ]; then
+		mkdir -p $ACTIVE_PROJECT/system/xbin
+		cp -R files/root/system/* $ACTIVE_PROJECT/system/
+		cp $ACTIVE_PROJECT/system/xbin/su $ACTIVE_PROJECT/system/xbin/daemonsu
+		mkdir -p $ACTIVE_PROJECT/system/bin/.ext
+		cp $ACTIVE_PROJECT/system/xbin/su $ACTIVE_PROJECT/system/bin/.ext/su
+		REBUILD_UPDATER-SCRIPT "ADD" "PERMISSIONS" "APPEND" "files/root/updater-script-PERMISSIONS"
+	else
+		rm -f $ACTIVE_PROJECT/system/app/Superuser.apk
+		rm -f $ACTIVE_PROJECT/system/xbin/su
+		rm -f $ACTIVE_PROJECT/system/xbin/daemonsu
+		rm -f $ACTIVE_PROJECT/system/bin/.ext/su
+		rm -f $ACTIVE_PROJECT/system/etc/init.d/99SuperSUDaemon
+		rm -f $ACTIVE_PROJECT/system/etc/.installed_su_daemon
+		REBUILD_UPDATER-SCRIPT "DEL" "PERMISSIONS" "u:object_r:su_exec:s0" #TODO1
+	fi
+	BUILD_UPDATER_SCRIPT
+}
+
 BUSYBOX() {
 	if [ ! -e $ACTIVE_PROJECT/system/xbin/busybox ]; then
 		mkdir -p $ACTIVE_PROJECT/system/xbin
 		cp files/busybox/busybox $ACTIVE_PROJECT/system/xbin/busybox
-		REBUILD_UPDATER-SCRIPT "ADD" "SYMLINK" "APPEND" 'symlink("/system/xbin/busybox", "/system/bin/busybox");'
-		REBUILD_UPDATER-SCRIPT "ADD" "TAIL" "PREPEND" 'run_program("/system/xbin/busybox", "--install", "-s", "/system/xbin");'
+		REBUILD_UPDATER-SCRIPT "ADD" "SYMLINK" "APPEND" "files/busybox/updater-script-SYMLINKS"
+		REBUILD_UPDATER-SCRIPT "ADD" "TAIL" "PREPEND" "files/busybox/updater-script-TAIL"
 	else
 		rm -f $ACTIVE_PROJECT/system/xbin/busybox
-		REBUILD_UPDATER-SCRIPT "DEL" "SYMLINK" "busybox" 'symlink("/system/xbin/busybox", "/system/bin/busybox");'
-		REBUILD_UPDATER-SCRIPT "DEL" "TAIL" "busybox" 'run_program("/system/xbin/busybox", "--install", "-s", "/system/xbin");'
+		REBUILD_UPDATER-SCRIPT "DEL" "SYMLINK" "busybox" #TODO1
+		REBUILD_UPDATER-SCRIPT "DEL" "TAIL" "busybox" #TODO1
 	fi
 	BUILD_UPDATER_SCRIPT
 }
@@ -375,17 +444,40 @@ while :; do
 		PRESS_ENTER
 		clear
 	fi
-	if [ ! -e $ACTIVE_PROJECT/system/xbin/busybox ]; then
-		echo "Busybox [NOT-INCLUDED]"
+
+	echo -n "Deodexed? "
+	if [ -e $ACTIVE_PROJECT/system/framework/framework.odex ]; then
+		echo "[NO]"
 	else
-		echo "Busybox [BUILT-IN]"
+		echo "[YES]"
 	fi
-	echo "b - Include/Remove Busybox"
-	echo "x - exit"
+	echo -n "Rooted? "
+	if [ ! -e $ACTIVE_PROJECT/system/xbin/su ]; then
+		echo "[NO]"
+	else
+		echo "[YES]"
+	fi
+	echo -n "Busybox? "
+	if [ ! -e $ACTIVE_PROJECT/system/xbin/busybox ]; then
+		echo "[NO]"
+	else
+		echo "[YES]"
+	fi
+
+	echo "d - Deodex (no way back!)"
+	echo "r - Add/Remove Root"
+	echo "b - Add/Remove Busybox"
+	echo "x - Exit"
 	read CHOICE
 	case "$CHOICE" in
 		"x")
 			exit 0
+			;;
+		"d")
+			DEODEX
+			;;
+		"r")
+			ROOT
 			;;
 		"b")
 			BUSYBOX
